'use client'

import Link from 'next/link'
import { Minus, Plus, Trash2 } from 'lucide-react'
import { PageHero } from '@/components/site/sections'
import { ButtonLink } from '@/components/site/button'
import { formatPrice } from '@/lib/products'
import { useCart } from '@/components/site/cart-provider'

export default function CartPage() {
  const { items, subtotal, setQty, remove } = useCart()
  return <main><PageHero eyebrow="Your basket" title={<>A considered collection of <em className="text-primary">support.</em></>} intro="Review your resources before continuing to checkout." breadcrumbs={[{ href: '/', label: 'Home' }, { label: 'Cart' }]} /><section className="container-site pb-24 md:pb-36">{items.length === 0 ? <div className="border border-border bg-secondary p-10 text-center"><h2 className="display text-4xl">Your basket is empty.</h2><p className="mx-auto mt-4 max-w-md leading-relaxed text-muted-foreground">Browse the shop to find a workbook, guide or worksheet for your next step.</p><ButtonLink href="/shop" size="lg" arrow="right" className="mt-8">Browse the shop</ButtonLink></div> : <div className="grid gap-12 md:grid-cols-12"><div className="divide-y divide-border md:col-span-8">{items.map(({ product, qty, lineTotal }) => <article key={product.slug} className="flex gap-5 py-6 first:pt-0"><div className="flex size-24 shrink-0 items-center justify-center bg-secondary text-center font-serif text-lg"><span>{product.category}</span></div><div className="min-w-0 flex-1"><Link href={`/shop/${product.slug}`} className="link-underline font-serif text-2xl">{product.name}</Link><p className="mt-1 text-sm text-muted-foreground">{formatPrice(product.price)}</p><div className="mt-4 flex items-center gap-3"><button type="button" onClick={() => setQty(product.slug, qty - 1)} className="flex size-8 items-center justify-center rounded-full border border-border" aria-label={`Decrease ${product.name}`}><Minus className="size-3" /></button><span className="w-4 text-center text-sm">{qty}</span><button type="button" onClick={() => setQty(product.slug, qty + 1)} className="flex size-8 items-center justify-center rounded-full border border-border" aria-label={`Increase ${product.name}`}><Plus className="size-3" /></button><button type="button" onClick={() => remove(product.slug)} className="ml-3 text-muted-foreground hover:text-foreground" aria-label={`Remove ${product.name}`}><Trash2 className="size-4" /></button></div></div><p className="text-sm tabular-nums">{formatPrice(lineTotal)}</p></article>)}</div><aside className="h-fit border border-border bg-secondary p-6 md:col-span-4 md:p-8"><p className="eyebrow text-muted-foreground">Order summary</p><div className="mt-6 flex justify-between border-t border-border pt-5"><span>Subtotal</span><span className="font-medium">{formatPrice(subtotal)}</span></div><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Digital resources are delivered by email after checkout.</p><ButtonLink href="/checkout" size="lg" className="mt-7 w-full">Continue to checkout</ButtonLink></aside></div>}</section></main>
}
